# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "conan"
    directory: "./"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "⬆ | upgrade: deps -"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
